Enable: false
MySQL:
  host: '127.0.0.1'
  port: '3306'
  database: 'minecraft'
  user: 'root'
  password: 'YourPassword'
Ban:
  Unban:
    Max: 2
Login:
  CheckUUID: true
  CheckName: true
  CheckBan: true
  AntiLoginName:
    - 'aux'
    - 'prn'
    - 'con'
    - 'nul'
    - 'lpt1'
    - 'lpt2'
    - 'lpt3'
    - 'lpt4'
    - 'lpt5'
    - 'lpt6'
    - 'lpt7'
    - 'lpt8'
    - 'lpt9'
    - 'com1'
    - 'com2'
    - 'com3'
    - 'com4'
    - 'com5'
    - 'com6'
    - 'com7'
    - 'com8'
    - 'com9'
DoublePlayer:
  Enable: false
  CheckTime: 2